apiVersion: apps/v1
kind: Deployment
metadata:
   name: node-mongo-deployment
   labels:
      appName: node-mongo-app
spec:
   replicas: 1
   selector:
     matchLabels:
        appName: node-mongo-app
   template:
      metadata:
         name: node-app-pod
         labels:
            appName: node-mongo-app
      spec:
         containers:
             - name: node-mongo
               image: kikuindocker/node-mongo-app
                

