apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    name: node-service
    app: node-mongo-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    appName: node-mongo-app